const K="daily-todos-v2",LK="daily-todos-v1",API="/api/store",TEST="/api/test-notification",D=document,S={store:load(),sel:key(new Date),filter:"all",search:"",notified:new Set,bg:false,st:0,nt:new Map},E={},IDS={di:"dateInput",pd:"prevDay",nd:"nextDay",tb:"todayBtn",tc:"totalCount",oc:"openCount",dc:"doneCount",pt:"progressText",pb:"progressBar",dl:"dateLabel",si:"searchInput",fm:"todoForm",ti:"titleInput",mi:"timeInput",pi:"priorityInput",gi:"tagInput",ri:"remindInput",xi:"repeatInput",ul:"todoList",tpl:"emptyTemplate",ns:"notificationStatus",en:"enableNotificationsBtn",tn:"testNotificationBtn",toast:"toast"};for(let k in IDS)E[k]=D.querySelector("#"+IDS[k]);E.filters=[...D.querySelectorAll(".filter")];
function load(){let e={days:{},recurring:[]};try{let c=JSON.parse(localStorage.getItem(K));if(c&&c.days&&Array.isArray(c.recurring))return c;let l=JSON.parse(localStorage.getItem(LK));if(l&&typeof l=="object")return{days:l,recurring:[]}}catch{return e}return e}
function norm(s){return s&&s.days&&Array.isArray(s.recurring)?s:s&&typeof s=="object"&&!Array.isArray(s)?{days:s,recurring:[]}: {days:{},recurring:[]}}
function has(s){s=norm(s);return Object.values(s.days).some(a=>Array.isArray(a)&&a.length)||s.recurring.length>0}
function save(){localStorage.setItem(K,JSON.stringify(S.store));clearTimeout(S.st);S.st=setTimeout(ssrv,250)}
async function lsrv(){try{let r=await fetch(API,{cache:"no-store"});if(!r.ok)throw Error();let x=await r.json();S.bg=true;if(has(x)){S.store=norm(x);localStorage.setItem(K,JSON.stringify(S.store))}else if(has(S.store))await ssrv()}catch{S.bg=false}render()}
async function ssrv(){let old=S.bg;try{let r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(S.store)});S.bg=r.ok;if(r.status===409)return await lsrv()}catch{S.bg=false}if(old!==S.bg)rN()}
function key(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function date(k){let [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d)}
function todos(k=S.sel){let a=(S.store.days[k]||[]).map(t=>({...t,source:"single"})),r=S.store.recurring.filter(t=>t.startDate<=k&&(!t.endDate||k<t.endDate)&&!t.deletedDates?.includes(k)).map(t=>({...t,...(t.dayState?.[k]||{}),source:"recurring",instanceDate:k}));return[...a,...r].sort(cmp)}
function cmp(a,b){return a.done!==b.done?+a.done-+b.done:a.time&&b.time?a.time.localeCompare(b.time):a.time?-1:b.time?1:new Date(a.createdAt)-new Date(b.createdAt)}
function setDay(a,k=S.sel){S.store.days[k]=a;save()}
function add(x){let t={id:crypto.randomUUID(),title:x.title,time:x.time,priority:x.priority,tag:x.tag,note:"",remind:x.remind,done:false,createdAt:new Date().toISOString()};x.repeatDaily?(S.store.recurring.push({...t,startDate:S.sel,dayState:{}}),save()):setDay([t,...(S.store.days[S.sel]||[])])}
function upd(t,p){if(t.source==="recurring"){let x=S.store.recurring.find(i=>i.id===t.id);if(!x)return;x.dayState=x.dayState||{};x.dayState[S.sel]={...(x.dayState[S.sel]||{}),...p};save()}else setDay((S.store.days[S.sel]||[]).map(i=>i.id===t.id?{...i,...p}:i))}
function del(t){if(t.source==="recurring"){let x=S.store.recurring.find(i=>i.id===t.id);if(!x)return;confirm("Delete all repeats? Cancel=today only")?S.store.recurring=S.store.recurring.filter(i=>i.id!==t.id):x.deletedDates=[...new Set([...(x.deletedDates||[]),S.sel])];save()}else setDay((S.store.days[S.sel]||[]).filter(i=>i.id!==t.id))}
function stop(t){let x=S.store.recurring.find(i=>i.id===t.id);if(x&&confirm("Stop repeat from today?")){x.endDate=S.sel;save()}}
function filtered(){let n=S.search.trim().toLowerCase();return todos().filter(t=>{let f=S.filter==="all"||S.filter==="open"&&!t.done||S.filter==="done"&&t.done||S.filter==="high"&&t.priority==="high"||S.filter==="repeat"&&t.source==="recurring";return f&&(!n||`${t.title} ${t.tag} ${t.note} ${t.time}`.toLowerCase().includes(n))})}
function pri(p){return{high:"High",normal:"Normal",low:"Low"}[p]||"Normal"}
function render(){let a=todos(),d=a.filter(t=>t.done).length,o=a.length-d,p=a.length?Math.round(d/a.length*100):0;E.di.value=S.sel;E.tc.textContent=a.length;E.oc.textContent=o;E.dc.textContent=d;E.pt.textContent=p+"%";E.pb.style.width=p+"%";E.dl.textContent=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"long"}).format(date(S.sel));E.filters.forEach(b=>b.classList.toggle("active",b.dataset.filter===S.filter));rN();list(filtered())}
function el(tag,cls,txt){let x=D.createElement(tag);if(cls)x.className=cls;if(txt!=null)x.textContent=txt;return x}
function list(a){E.ul.replaceChildren();if(!a.length)return E.ul.append(E.tpl.content.cloneNode(true));a.forEach(t=>{let li=el("li",`todo-item${t.done?" done":""}${due(t)?" due":""}`),chk=el("button",`check-btn${t.done?" is-done":""}`,t.done?"\u2713":""),main=el("div","todo-main"),row=el("div","todo-title-row"),act=el("div","todo-actions"),note=el("textarea","note");chk.type="button";chk.title=t.done?"Undone":"Done";chk.onclick=()=>{upd(t,{done:!t.done});render()};row.append(el("span","time-pill",t.time||"No time"),el("span","todo-title",t.title),el("span","badge "+t.priority,pri(t.priority)));if(t.source==="recurring")row.append(el("span","repeat-pill","Daily"));if(t.remind&&t.time)row.append(el("span","remind-pill","Bell"));else if(t.time&&!t.done)row.append(el("span","no-remind-pill","No bell"));if(t.tag)row.append(el("span","tag","#"+t.tag));note.placeholder="Note";note.value=t.note||"";note.oninput=()=>later(t,note.value);main.append(row,el("div","todo-meta",fmt(t.createdAt)),note);if(t.source==="recurring"){let b=el("button","stop-btn","Stop");b.type="button";b.title="Stop daily repeat";b.onclick=()=>{stop(t);render()};act.append(b)}let db=el("button","delete-btn","Del");db.type="button";db.title="Delete";db.onclick=()=>{del(t);render()};act.append(db);li.append(chk,main,act);E.ul.append(li)})}
function later(t,n){let k=`${t.source}-${t.instanceDate||S.sel}-${t.id}`;clearTimeout(S.nt.get(k));S.nt.set(k,setTimeout(()=>{upd(t,{note:n});S.nt.delete(k)},650))}
function shift(n){let d=date(S.sel);d.setDate(d.getDate()+n);S.sel=key(d);render()}
function rN(){if(S.bg){E.ns.textContent="Background connected";E.en.disabled=true;E.tn.disabled=false;return}if(!support()){E.ns.textContent="Notifications unsupported";E.en.disabled=E.tn.disabled=true;return}let p=Notification.permission,m={granted:"Notifications on",denied:"Notifications blocked",default:"Enable notifications"};E.ns.textContent=m[p]||"Notification state unknown";E.en.disabled=p==="granted"||p==="denied";E.tn.disabled=p!=="granted"}
function support(){return"Notification"in window&&window.isSecureContext}
async function enN(){if(!support())return toast("Open via localhost"),rN();let p=await Notification.requestPermission();rN();p==="granted"?(sys("Todo notifications on","Reminders will notify."),toast("Notifications on")):toast(p==="denied"?"Notifications blocked":"Notifications not on")}
function tN(){if(S.bg)return fetch(TEST,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error();toast("Background test sent")}).catch(()=>{S.bg=false;rN();toast("Background unavailable")});toast(sys("Todo test","Notifications work")?"Test sent":"Enable notifications first");rN()}
function chk(){let n=new Date,t=key(n),m=n.getHours()*60+n.getMinutes();todos(t).forEach(x=>{if(!x.time||!x.remind||x.done)return;let [h,mm]=x.time.split(":").map(Number),tm=h*60+mm,k=`${t}-${x.id}-${x.time}`;if(m>=tm&&m<=tm+5&&!S.notified.has(k)){S.notified.add(k);notify(x)}})}
function notify(t){let m=`${t.time} ${t.title}`;sys("Todo reminder",m);toast("Reminder: "+m)}
function sys(title,body){if(!support()||Notification.permission!=="granted")return false;new Notification(title,{body,tag:`daily-todo-${title}-${body}`,renotify:true,requireInteraction:true});return true}
function toast(m){E.toast.textContent=m;E.toast.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>E.toast.classList.remove("show"),4200)}
function fmt(v){return v?new Date(v).toLocaleString("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):""}
function due(t){if(S.sel!==key(new Date)||!t.time||t.done)return false;let n=new Date,[h,m]=t.time.split(":").map(Number),d=h*60+m-(n.getHours()*60+n.getMinutes());return d>=0&&d<=30}
E.fm.onsubmit=e=>{e.preventDefault();let title=E.ti.value.trim();if(!title)return;add({title,time:E.mi.value,priority:E.pi.value,tag:E.gi.value.trim(),remind:E.ri.checked,repeatDaily:E.xi.checked});E.fm.reset();E.pi.value="normal";E.ri.checked=true;E.ti.focus();render()};E.di.onchange=()=>{S.sel=E.di.value||key(new Date);render()};E.pd.onclick=()=>shift(-1);E.nd.onclick=()=>shift(1);E.tb.onclick=()=>{S.sel=key(new Date);render()};E.si.oninput=()=>{S.search=E.si.value;render()};E.filters.forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;render()});E.en.onclick=enN;E.tn.onclick=tN;render();lsrv();chk();setInterval(chk,3e4);
