param([Parameter(Mandatory=$true)][string]$ShortcutPath,[Parameter(Mandatory=$true)][string]$TargetPath,[Parameter(Mandatory=$true)][string]$AppId,[string]$Description="Daily Todo",[string]$WorkingDirectory="",[string]$Arguments="",[string]$IconPath="",[int]$IconIndex=0)
$ErrorActionPreference="Stop"
$d=Split-Path -Parent $ShortcutPath;if(!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null}
$s=New-Object -ComObject WScript.Shell;$l=$s.CreateShortcut($ShortcutPath);$l.TargetPath=$TargetPath;$l.Arguments=$Arguments;$l.WorkingDirectory=$WorkingDirectory;$l.Description=$Description;if($IconPath){$l.IconLocation="$IconPath,$IconIndex"};$l.Save()
try{
$c=@"
using System;using System.Runtime.InteropServices;public class A{[DllImport("shell32.dll",CharSet=CharSet.Unicode,PreserveSig=false)]static extern void SHGetPropertyStoreFromParsingName(string n,IntPtr b,uint f,ref Guid r,out IPropertyStore p);[StructLayout(LayoutKind.Sequential,Pack=4)]public struct K{public Guid f;public uint p;}[StructLayout(LayoutKind.Explicit)]public struct V{[FieldOffset(0)]public ushort vt;[FieldOffset(8)]public IntPtr pv;}[ComImport,Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]public interface IPropertyStore{uint GetCount(out uint c);uint GetAt(uint i,out K k);uint GetValue(ref K k,out V v);uint SetValue(ref K k,ref V v);uint Commit();}[DllImport("ole32.dll")]static extern int PropVariantClear(ref V v);public static void Set(string path,string app){var id=new Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99");IPropertyStore ps;SHGetPropertyStoreFromParsingName(path,IntPtr.Zero,2,ref id,out ps);var k=new K{f=new Guid("9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3"),p=5};var v=new V{vt=31,pv=Marshal.StringToCoTaskMemUni(app)};try{ps.SetValue(ref k,ref v);ps.Commit();}finally{PropVariantClear(ref v);}}}
"@
Add-Type -TypeDefinition $c -Language CSharp;[A]::Set($ShortcutPath,$AppId)
}catch{Write-Verbose "AppUserModelID best-effort registration failed: $_"}
